### ISSUE TITLE
touch id

### ISSUE THREAD

**Issue by natxopedreira** [nneonneo/ofxWin8Touch#2]
Hi

The touch.id its a unique value that increments from time..... Its there a way to change that so that the id of the touch its constant?

I means:
- first touch has an id of 0
- second has an id of 1
  +.....

So its more like the number of touch in this moment, i want this because in oF mobile implementation (android and iOS) the touch.id works in this way. And i can use a gestures addon to have pinch, pan,.... right now i can not make the gestures works with this because the touch.id implementation

thanks!

**Comment by nneonneo** [comment]
Which gesture addon has a problem with this? Generally, I don't believe touch.id has a consistent implementation across platforms, so relying on its value (instead of just using it to track a single touch over time) is probably not a good idea.

**Comment by mccap079** [comment]
yeah, i'm on win10 and `touch.id` persists at the os level, counting the number of touches since boot. since i already did the work, here's example_basic with a new `touches` container for current touches only: [src.zip](https://github.com/nneonneo/ofxWin8Touch/files/3149178/src.zip)
